# User config
author: "Transpacific Food Coop"
tagline: "A collective supporting Asian food culture and businesses"
description: "This is a global directory that collects local directories of Asian eateries. While this project began to support East Asian businesses facing racism and tough times during Covid-19, we welcome all Asian communities. From Korea down to Indonesia, Japan, through the Middle East."
keywords: "local Asian restaurants"
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/transpacific-food-coop"

# Site config
baseurl: "/transpacific-food-coop.github.io"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed