# Site Config (including for SEO)
author: "Transpacific Food Coop"
title: "Asian Eats Directory"
tagline: "A collection of Asian food directories to support the global diaspora"

description: "Where to buy Asian food near you, a global directory of directories. Support your local Asian businesses facing undue racism and discrmination! Submissions welcome!"
keywords: "local Asian restaurants"
email: "contact@transpacificfoodcoop.com"
logo: /favicon-16x16.png
image: /assets/images/AsianEatsDirectory.png

# Social (includes SEO)
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/transpacific-food-coop"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Plugins
plugins: [jekyll-seo-tag]