# Site Config (including for SEO)
author: "Transpacific Food Coop"
title: "Asian Eats Directory"
tagline: "A collection of Asian food directories to support the global diaspora"

description: "Supporting the global Asian diaspora by showcasing community lists, maps, and directories of Asian eateries. Our solidarity extends to all Asian communities. Explore and add yours!
keywords: "local Asian restaurants"
email: "contact@transpacificfoodcoop.com"
logo: /favicon-16x16.png
image: /assets/images/AsianEatsDirectory.png

# Social (includes SEO)
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/transpacific-food-coop"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed

# Plugins
plugins: [jekyll-seo-tag]
  
